#!/bin/bash

update_repo() {
    git stash
    git pull --force
    git submodule update --init --recursive
}

if [[ "$1" == "-c" ]]; then
    update_repo
    bash run.sh --3
else
    bash run.sh --3
fi
